name: Python package

on:
  #schedule:
  #  - cron: '* 8 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Pre Release
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: "3.10"
      - name: Install tox-gh
        run: pip install tox-gh
      - name: Setup test environment
        run: tox run --notest
      - name: Test with PyTest
        run: tox run
      - name: Test building package
        run: tox run -e build